name: Windows Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Install dependencies with Poetry
        run: |
          poetry config virtualenvs.create false
          poetry install --only main

      - name: Build the application with PyInstaller
        run: |
          poetry run pyinstaller --onefile --name SpeechJokey src/main.py

      - name: Add kivy_deps to spec
        run: |
          (Get-Content -Path SpeechJokey.spec) -replace '^', 'from kivy_deps import sdl2, glew`n' | Set-Content -Path SpeechJokey.spec
      
      - name: Add source tree to spec
        run: |
          (Get-Content -Path SpeechJokey.spec) -replace 'COLLECT\(exe,', 'COLLECT(exe,`n    Tree('"'"'src\\'"'"'),' | Set-Content -Path SpeechJokey.spec
      
      - name: Add dependency tree to spec
        run: |
          (Get-Content -Path SpeechJokey.spec) -replace 'a.datas,', 'a.datas,`n    *[Tree(p) for p in (sdl2.dep_bins + glew.dep_bins)],' | Set-Content -Path SpeechJokey.spec
      
      - name: Build the spec with PyInstaller
        run: |
          poetry run pyinstaller SpeechJokey.spec

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: windows-executable
          path: dist/SpeechJokey/*.exe
